# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name rcpp_sum
#' @title A sum function using Rcpp
NULL

rcpp_sum <- function(v) {
    .Call(`_SA23204193_rcpp_sum`, v)
}

